### ISSUE TITLE
No new device found

### ISSUE THREAD

**Issue by madskristensen** [toddaustin07/webrequestor#2]
Hi Todd, I just installed the Web Requestor driver from your channel, but ST isn't finding the device after it scans for new devices. I tried uninstalling and reinstalling the driver again, but that made no difference. Could a recent update have broken the auto-creation mechanism?

**Comment by toddaustin07** [comment]
Hi there; sorry for the long delay in responding.

Web requestor does not "discover" devices.  It is used to configure HTTP requests manually that can then be triggered via mobile app or automations.

Maybe you have this confused with another driver?

**Comment by madskristensen** [comment]
Sorry for haven't closed it down. It showed up and installed just fine about a week later. I've successfully used it for controlling several of my LAN devices. Thank you!
