### ISSUE TITLE
Doesn't "find" new device "Web Request Multi Master"

### ISSUE THREAD

**Issue by rajid** [toddaustin07/webrequestor#8]
Hi!  My V3 smartthings hub was recently upgraded and now I'm looking for a replacement for the special web URI requester handler which I had previously.  (I have a number of older X10 devices which I was controlling via a web interface.)
I found your handler and followed your instructions to add it to my hub.  I have verified that the handler is, indeed, installed on my hub.  I'm stuck when I get to the instructions:

"When the driver gets installed onto your hub, you can do an Add device / Scan for nearby devices and a new device called ‘Web Req Multi Master’ will be created in your ‘No room assigned’ room."

I'm on an iPhone.  I open the SmartThings app and do "add device" and then "Scan for nearby devices".  It twirls for a while and then reports that it found nothing and no new 'Web Req Multi Master' device has been added in my "no room assigned" room.

I'm sure I'm missing something obvious!  What is it?

**Comment by toddaustin07** [comment]
Hello.  A change occurred in the SmartThings app where newly created devices are now placed in the same room that contains your hub device, instead of "No room assigned".

You will hopefully find the webrequestor device there.

I need to update the Readme file!
