### ISSUE TITLE
Web Request Body case sensitivity issue

### ISSUE THREAD

**Issue by timttran** [toddaustin07/webrequestor#9]
The body of the Web Request always automatically capitalize the very first character of the JSON value pair.  For example, the desired JSON value pair is {"on":true}, it changes it to {"On":true} as soon as it's Saved.  This causes problem for the endpoint to resolve the payload when case sensitivity is critical.  

I cannot find a way to overcome this problem.

**Comment by toddaustin07** [comment]
The app has a bad habit of automatically capitalizing words when shown in the Settings screen.  However if you edit the field, you may find that it is not actually capitalized.  You fine otherwise, please let me know, since that would be a SmartThings bug.

**Comment by toddaustin07** [comment]
One other thought:  assuming the body data isn't really being capitalizing (just appearing to be in the app screen), that means there is some OTHER reason why your device is rejecting the HTTP request.  Something to be very careful about is to use regular "straight" double-quote characters and not the right and left kind.  You may have to be careful to select the right quote character on your mobile device.  On iOS, for example, you long press the quote key on the keyboard and then select the specific style.

Also, maybe your device is expecting a header of Content-Type=application/json, which you may need to add to the headers field in the preconfigured request.

**Comment by timttran** [comment]
thanks Todd....I'll try again.

I did confirm it with another tool (Postman) with the first character cap'ed and got the same error message.

**Comment by toddaustin07** [comment]
Hi - Just confirming if you consider this issue resolved?

**Comment by timttran** [comment]
Yes....please close it.  Thanks Todd
________________________________
